# Generated by Django 5.2.7 on 2025-10-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(db_index=True, max_length=255, unique=True)),
                ("image", models.ImageField(upload_to="uploads/")),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
